#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

if ! command -v podman >/dev/null 2>&1; then
  echo "ERROR: podman not found. Install podman, or build via GitHub Actions." >&2
  exit 1
fi

IMAGE="${ESPHOME_IMAGE:-ghcr.io/esphome/esphome:stable}"
CFG_DIR="$ROOT_DIR/esphome"
OUT_DIR="$ROOT_DIR/artifacts"

mkdir -p "$OUT_DIR"

tmp="$(mktemp -d)"
cleanup() { rm -rf "$tmp"; }
trap cleanup EXIT

# Copy config to a temp dir so we never mutate tracked files during build.
rsync -a --delete "$CFG_DIR/" "$tmp/config/"

secrets_src="$CFG_DIR/secrets.yaml"
if [[ -f "$secrets_src" ]]; then
  rsync -a "$secrets_src" "$tmp/config/secrets.yaml"
else
  # Generate build-time secrets so we can produce a usable firmware without keeping secrets in git.
  api_key="$(openssl rand -base64 32)"
  ota_password="$(openssl rand -hex 16)"
  wifi_ap_password="${WIFI_AP_PASSWORD:-hvplc-setup-1234}"

  cat >"$tmp/config/secrets.yaml" <<EOF
# Build-time secrets (generated by tools/build_factory.sh)
wifi_ap_password: "${wifi_ap_password}"
api_key: "${api_key}"
ota_password: "${ota_password}"
EOF

  ts="$(date -u +%Y%m%dT%H%M%SZ)"
  creds="$OUT_DIR/stamplc-humidifier-${ts}.secrets.txt"
  {
    echo "wifi_ap_password=${wifi_ap_password}"
    echo "api_key=${api_key}"
    echo "ota_password=${ota_password}"
  } >"$creds"
  chmod 600 "$creds" || true
fi

echo "Pulling $IMAGE ..."
podman pull "$IMAGE" >/dev/null

echo "Building factory firmware..."
podman run --rm \
  -v "$ROOT_DIR/.cache/esphome:/cache:Z" \
  -v "$tmp/config:/config:Z" \
  -w /config \
  "$IMAGE" \
  compile stamplc_humidifier.yaml

factory_bin="$(find "$tmp/config/.esphome/build" -type f -name 'firmware.factory.bin' | head -n 1 || true)"
ota_bin="$(find "$tmp/config/.esphome/build" -type f -name 'firmware.ota.bin' | head -n 1 || true)"

if [[ -z "${factory_bin:-}" ]]; then
  echo "ERROR: build succeeded but firmware.factory.bin was not found under .esphome/build" >&2
  exit 1
fi

ts="$(date -u +%Y%m%dT%H%M%SZ)"
cp -f "$factory_bin" "$OUT_DIR/stamplc-humidifier-${ts}.factory.bin"

if [[ -n "${ota_bin:-}" ]]; then
  cp -f "$ota_bin" "$OUT_DIR/stamplc-humidifier-${ts}.ota.bin"
fi

echo "Wrote:"
ls -la "$OUT_DIR" | sed -n '1,200p'
